x-node: &node
  image: tommy/platoon
  networks:
    - shared
  expose:
    - 5001

services:
  node1:
    <<: *node
    environment:
      - NODE_ID=1
      - RUST_LOG=info
    ports:
      - 8001:8001
  node2:
    <<: *node
    environment:
      - NODE_ID=2
      - RUST_LOG=info
    ports:
      - 8002:8001
  node3:
    <<: *node
    environment:
      - NODE_ID=3
      - RUST_LOG=info
    ports:
      - 8003:8001
networks:
  shared:
    driver: "bridge"
