x-node: &node
  image: tommy/platoon
  networks:
    - shared
  expose:
    - 5001
  depends_on:
    - logger

services:
  node1:
    <<: *node
    environment:
      - NODE_ID=1
      - CLUSTER_SIZE=3
      - RUST_LOG=info
      - RAFT_SERVER_PORT=5001
      - PLATOON_SERVER_PORT=8001
      - RND_SEED=123123123
      - READ_PERIOD=500
      - WRITE_PERIOD=1000
    ports:
      - 8001:8001
  node2:
    <<: *node
    environment:
      - NODE_ID=2
      - CLUSTER_SIZE=3
      - RUST_LOG=info
      - RAFT_SERVER_PORT=5001
      - PLATOON_SERVER_PORT=8001
      - RND_SEED=456456456
      - READ_PERIOD=500
      - WRITE_PERIOD=1000
    ports:
      - 8002:8001
  node3:
    <<: *node
    environment:
      - NODE_ID=3
      - CLUSTER_SIZE=3
      - RUST_LOG=info
      - RAFT_SERVER_PORT=5001
      - PLATOON_SERVER_PORT=8001
      - RND_SEED=789789789
      - READ_PERIOD=500
      - WRITE_PERIOD=1000
    ports:
      - 8003:8001
  logger:
    image: grafana/loki:3.4.1
    expose:
      - 3100
    networks:
      - shared
    depends_on:
      - viewer
  viewer:
    image: grafana/grafana:8.2.1
    ports:
      - 3000:3000
    networks:
      - shared
networks:
  shared:
    driver: "bridge"
