steps:
  # Build and push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/platoon:latest", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/platoon:latest"]

  # Deploy infrastructure with Terraform
  # - name: "hashicorp/terraform:1.5.0"
  #   entrypoint: "/bin/sh"
  #   args:
  #     - "-c"
  #     - |
  #       terraform init
  #       terraform apply -var="project_id=$PROJECT_ID" -var="node_count=3" -auto-approve

images:
  - "gcr.io/$PROJECT_ID/platoon:latest"

timeout: 1800s
